import type { Product, Order, OrderItem, Wholesaler, Affiliate, Referral, SalesRep } from "@/types/database";

// Mock sales representatives
export const mockSalesReps: SalesRep[] = [
  {
    id: "sr1",
    name: "Amina Hassan",
    phone: "+254712345001",
    whatsapp_phone: "254712345001",
    email: "amina@stocklink.co",
    avatar_url: null,
    bio: "Nairobi region specialist. 5+ years in wholesale distribution.",
    is_active: true,
    created_at: "2025-01-01T08:00:00Z",
  },
  {
    id: "sr2",
    name: "Brian Kipchoge",
    phone: "+254712345002",
    whatsapp_phone: "254712345002",
    email: "brian@stocklink.co",
    avatar_url: null,
    bio: "Coast & Mombasa rep. Expert in bulk food supplies.",
    is_active: true,
    created_at: "2025-01-01T08:00:00Z",
  },
  {
    id: "sr3",
    name: "Grace Akinyi",
    phone: "+254712345003",
    whatsapp_phone: "254712345003",
    email: "grace@stocklink.co",
    avatar_url: null,
    bio: "Western Kenya rep. Covers Kisumu and surrounding areas.",
    is_active: true,
    created_at: "2025-01-01T08:00:00Z",
  },
];

// Mock wholesalers
export const mockWholesalers: Wholesaler[] = [
  {
    id: "w1",
    name: "Nairobi Premium Supplies",
    location: "Industrial Area, Nairobi",
    phone: "+254700111111",
    sales_rep_id: "sr1",
    created_at: "2025-01-15T08:00:00Z",
  },
  {
    id: "w2",
    name: "Mombasa Coast Trading",
    location: "Changamwe, Mombasa",
    phone: "+254700222222",
    sales_rep_id: "sr2",
    created_at: "2025-02-10T08:00:00Z",
  },
  {
    id: "w3",
    name: "Kisumu Lake Distributors",
    location: "Kibuye, Kisumu",
    phone: "+254700333333",
    sales_rep_id: "sr3",
    created_at: "2025-03-05T08:00:00Z",
  },
];

// Mock products — wholesale/bulk items with MOQ
export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Soko Pishori Rice 25kg",
    description:
      "Premium long-grain Pishori rice, sourced from Mwea. Factory-sealed 25kg bags. Minimum order 5 bags.",
    category: "rice",
    price: 3200,
    unit: "bag",
    min_order_qty: 5,
    stock: 450,
    image_url: "/images/rice.jpg",
    wholesaler_id: "w1",
    is_trending: true,
    is_flash_deal: false,
    flash_deal_price: null,
    flash_deal_expires_at: null,
    location: "Industrial Area, Nairobi",
    created_at: "2025-06-01T08:00:00Z",
    updated_at: "2025-12-20T10:30:00Z",
  },
  {
    id: "p2",
    name: "Golden Fry Cooking Oil 20L",
    description:
      "Refined vegetable cooking oil in 20-litre jerrycans. Ideal for restaurants and retailers. Minimum order 3 jerrycans.",
    category: "oil",
    price: 4500,
    unit: "jerrycan",
    min_order_qty: 3,
    stock: 200,
    image_url: "/images/oil.jpg",
    wholesaler_id: "w1",
    is_trending: true,
    is_flash_deal: true,
    flash_deal_price: 3800,
    flash_deal_expires_at: "2026-04-03T23:59:59Z",
    location: "Industrial Area, Nairobi",
    created_at: "2025-07-15T08:00:00Z",
    updated_at: "2025-12-18T14:00:00Z",
  },
  {
    id: "p3",
    name: "Mumias Sugar 50kg",
    description:
      "White refined sugar, 50kg bags. Factory-sealed for freshness. Minimum order 10 bags.",
    category: "sugar",
    price: 6800,
    unit: "bag",
    min_order_qty: 10,
    stock: 120,
    image_url: "/images/sugar.jpg",
    wholesaler_id: "w2",
    is_trending: false,
    is_flash_deal: false,
    flash_deal_price: null,
    flash_deal_expires_at: null,
    location: "Changamwe, Mombasa",
    created_at: "2025-08-20T08:00:00Z",
    updated_at: "2025-12-15T09:00:00Z",
  },
  {
    id: "p4",
    name: "Jogoo Maize Flour 2kg x 12",
    description:
      "Carton of 12 × 2kg packets of maize flour. Staple for ugali preparation. Minimum order 10 cartons.",
    category: "flour",
    price: 1800,
    unit: "carton",
    min_order_qty: 10,
    stock: 800,
    image_url: "/images/flour.jpg",
    wholesaler_id: "w2",
    is_trending: true,
    is_flash_deal: false,
    flash_deal_price: null,
    flash_deal_expires_at: null,
    location: "Changamwe, Mombasa",
    created_at: "2025-09-10T08:00:00Z",
    updated_at: "2025-12-19T11:00:00Z",
  },
  {
    id: "p5",
    name: "Total LPG Gas 13kg",
    description:
      "13kg liquefied petroleum gas cylinders. Full refill with safety valve check. Minimum order 5 cylinders.",
    category: "lpg",
    price: 2950,
    unit: "cylinder",
    min_order_qty: 5,
    stock: 50,
    image_url: "/images/lpg.jpg",
    wholesaler_id: "w3",
    is_trending: false,
    is_flash_deal: true,
    flash_deal_price: 2600,
    flash_deal_expires_at: "2026-04-02T18:00:00Z",
    location: "Kibuye, Kisumu",
    created_at: "2025-10-05T08:00:00Z",
    updated_at: "2025-12-21T08:30:00Z",
  },
  {
    id: "p6",
    name: "Brookside Fresh Milk 500ml x 24",
    description:
      "Carton of 24 × 500ml packets of fresh pasteurized milk. Cold chain maintained. Minimum order 5 cartons.",
    category: "dairy",
    price: 2400,
    unit: "carton",
    min_order_qty: 5,
    stock: 150,
    image_url: "/images/milk.jpg",
    wholesaler_id: "w1",
    is_trending: false,
    is_flash_deal: false,
    flash_deal_price: null,
    flash_deal_expires_at: null,
    location: "Industrial Area, Nairobi",
    created_at: "2025-11-01T08:00:00Z",
    updated_at: "2025-12-22T07:00:00Z",
  },
  {
    id: "p7",
    name: "Coca-Cola 500ml x 24",
    description:
      "Crate of 24 × 500ml bottles of Coca-Cola. Chilled delivery available. Minimum order 10 crates.",
    category: "beverages",
    price: 1650,
    unit: "crate",
    min_order_qty: 10,
    stock: 600,
    image_url: "/images/soda.jpg",
    wholesaler_id: "w3",
    is_trending: true,
    is_flash_deal: false,
    flash_deal_price: null,
    flash_deal_expires_at: null,
    location: "Kibuye, Kisumu",
    created_at: "2025-11-15T08:00:00Z",
    updated_at: "2025-12-20T16:00:00Z",
  },
  {
    id: "p8",
    name: "Omo Detergent 5kg x 6",
    description:
      "Carton of 6 × 5kg economy packs. Multi-active cleaning detergent. Minimum order 5 cartons.",
    category: "cleaning",
    price: 7200,
    unit: "carton",
    min_order_qty: 5,
    stock: 0,
    image_url: "/images/detergent.jpg",
    wholesaler_id: "w2",
    is_trending: false,
    is_flash_deal: false,
    flash_deal_price: null,
    flash_deal_expires_at: null,
    location: "Changamwe, Mombasa",
    created_at: "2025-12-01T08:00:00Z",
    updated_at: "2025-12-22T12:00:00Z",
  },
];

// Mock orders — bulk purchase orders from retailers
export const mockOrders: Order[] = [
  {
    id: "ord1",
    retailer_id: "r1",
    status: "delivered",
    total: 64000,
    delivery_address: "Shop 12, Gikomba Market, Nairobi",
    payment_method: "mpesa",
    notes: null,
    created_at: "2025-12-18T09:00:00Z",
    updated_at: "2025-12-19T14:30:00Z",
  },
  {
    id: "ord2",
    retailer_id: "r1",
    status: "out_for_delivery",
    total: 22500,
    delivery_address: "Shop 12, Gikomba Market, Nairobi",
    payment_method: "cash",
    notes: "Leave at back entrance",
    created_at: "2025-12-21T11:00:00Z",
    updated_at: "2025-12-22T08:00:00Z",
  },
  {
    id: "ord3",
    retailer_id: "r1",
    status: "confirmed",
    total: 68000,
    delivery_address: "Mama Mboga Kiosk, Tom Mboya St, Nairobi",
    payment_method: "mpesa",
    notes: null,
    created_at: "2025-12-22T07:30:00Z",
    updated_at: "2025-12-22T09:00:00Z",
  },
  {
    id: "ord4",
    retailer_id: "r2",
    status: "placed",
    total: 16000,
    delivery_address: "Kiosk 5, Eastleigh Market, Nairobi",
    payment_method: "cash",
    notes: "Call before delivery",
    created_at: "2025-12-22T12:00:00Z",
    updated_at: "2025-12-22T12:00:00Z",
  },
];

// Mock order items — bulk quantities
export const mockOrderItems: OrderItem[] = [
  {
    id: "oi1",
    order_id: "ord1",
    product_id: "p1",
    quantity: 20,
    unit_price: 3200,
    total_price: 64000,
  },
  {
    id: "oi2",
    order_id: "ord2",
    product_id: "p2",
    quantity: 5,
    unit_price: 4500,
    total_price: 22500,
  },
  {
    id: "oi3",
    order_id: "ord3",
    product_id: "p3",
    quantity: 10,
    unit_price: 6800,
    total_price: 68000,
  },
  {
    id: "oi4",
    order_id: "ord4",
    product_id: "p1",
    quantity: 5,
    unit_price: 3200,
    total_price: 16000,
  },
];

// Mock affiliates
export const mockAffiliates: Affiliate[] = [
  {
    id: "aff1",
    user_id: "user-abc-123",
    code: "SARAH2025",
    name: "Sarah Wanjiku",
    email: "sarah@example.com",
    commission_rate: 0.02,
    total_earnings: 4320,
    total_paid: 2000,
    total_clicks: 187,
    total_referrals: 12,
    status: "active",
    created_at: "2025-06-01T08:00:00Z",
  },
  {
    id: "aff2",
    user_id: "user-def-456",
    code: "JAMES2025",
    name: "James Ochieng",
    email: "james@example.com",
    commission_rate: 0.02,
    total_earnings: 1860,
    total_paid: 1000,
    total_clicks: 95,
    total_referrals: 6,
    status: "active",
    created_at: "2025-07-15T08:00:00Z",
  },
];

// Mock referrals / commissions
export const mockReferrals: Referral[] = [
  {
    id: "ref1",
    affiliate_id: "aff1",
    order_id: "ord1",
    referred_user_id: "user-r1",
    order_total: 64000,
    commission: 1280,
    status: "paid",
    created_at: "2025-08-10T11:00:00Z",
  },
  {
    id: "ref2",
    affiliate_id: "aff1",
    order_id: "ord2",
    referred_user_id: "user-r2",
    order_total: 28000,
    commission: 560,
    status: "approved",
    created_at: "2025-09-05T14:30:00Z",
  },
  {
    id: "ref3",
    affiliate_id: "aff1",
    order_id: "ord3",
    referred_user_id: "user-r3",
    order_total: 68000,
    commission: 1360,
    status: "pending",
    created_at: "2025-10-20T09:15:00Z",
  },
  {
    id: "ref4",
    affiliate_id: "aff1",
    order_id: "ord4",
    referred_user_id: "user-r4",
    order_total: 56000,
    commission: 1120,
    status: "pending",
    created_at: "2025-11-02T16:45:00Z",
  },
  {
    id: "ref5",
    affiliate_id: "aff2",
    order_id: null,
    referred_user_id: "user-r5",
    order_total: 42000,
    commission: 840,
    status: "approved",
    created_at: "2025-10-01T10:00:00Z",
  },
  {
    id: "ref6",
    affiliate_id: "aff2",
    order_id: null,
    referred_user_id: "user-r6",
    order_total: 51000,
    commission: 1020,
    status: "pending",
    created_at: "2025-11-10T12:00:00Z",
  },
];
